# Generated by Django 6.0.7 on 2026-08-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_approval_status_listing_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='floors',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Số tầng', null=True),
        ),
    ]
