# Generated by Django 6.0.7 on 2026-08-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_floors'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
