# Generated by Django 6.0.7 on 2026-08-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={},
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
